version: "3"
services:
  api:
    build: .
    environment:
      - NODE_ENV=production
    depends_on: 
      - postgres
    ports:
      - "1337:1337"
    links:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres